import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono, JetBrains_Mono, Oswald } from "next/font/google";
import { AuthProvider } from "./auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  variable: "--font-Oswald",
  weight: "700",

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gym App",
  description: "Generated by create next app",
};
const Jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jetbrains-mono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Jetbrains.variable} ${oswald.variable} antialiased  w-screen overflow-x-hidden `}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
